name: Check config grammar changes (PR)

permissions:
  pull-requests: write

on:
  pull_request:

jobs:
  check-cfg-grammar-changes:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: syslog-ng/syslog-ng-cfg-diff-pr@v1
        continue-on-error: true
